repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - args:
    - --unsafe
    id: check-yaml
  - args:
    - --maxkb=50000
    - --enforce-all
    id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
- hooks:
  - args:
    - --fix
    id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.7
- hooks:
  - exclude: tests/
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.901
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
